### ISSUE TITLE
Attachment issue - Archive

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM-Outlook-Plugin#1]
If you archive email via plugin, it doesn't save you attachments, which was with email

**Comment by rivermandk** [comment]
Or it only save some of the attachments. Has not been able to successfully save an e-mail with a large PDF attached and the reopen it in SuiteCRM. 
NB: Otherwise it is a great product :-) :-)

**Comment by dgreeninger** [comment]
I'm using Outlook 2010 and encountering the same issue. 
Are there file size requirements?

**Comment by h5stanfill** [comment]
I am using Outlook 2010 and encountering the same issue. I can not attach the email attachments via Archive..... Please assist.

**Comment by mayerelyashiv** [comment]
Hi, any updates about this?

**Comment by pgorod** [comment]
@willrennie, I'm really impressed by your new Github avatar! That is one cool CRM cat.

But I'm afraid that's not the reason I'm mentioning you here... since you seem to be the author of this Plugin code, can you please take a look at this thread?:
https://suitecrm.com/forum/suitecrm-outlook-plugin/10030-attachments-aren-t-saved-on-suitecrm
(posts #35155 and #35156)

we are getting to a point where I think the bug is discovered and a simple fix could be applied. I don't have an easy way to set up Visual Studio and run this project to test the fix, though. I don't even use the plugin, I just got involved in this while trying to help in the forums...

I don't know if the problem in that forum thread is exactly the problem reported here by others... it looks similar, but I can't be sure.

**Comment by mayerelyashiv** [comment]
Hi,
i have these logs error:

```
------------------11/07/2016 08:44:45-----------------
AddInModule.Base64Encode method COM Exception:
Message:Impossibile salvare l'allegato. Impossibile aggiungere l'allegato. Nessuna origine dati specificata.
Source:Microsoft Outlook
StackTrace:   at Microsoft.Office.Interop.Outlook.Attachment.SaveAsFile(String Path)
   at SuiteCRMAddIn.ThisAddIn.Base64Encode(Attachment objMailAttachment, MailItem objMail)
Data:System.Collections.ListDictionaryInternal
HResult:-2147467259
Inputs:
Data:image001.png
-------------------------------------------------------------------------

------------------11/07/2016 08:44:45-----------------
AddInModule.Base64Encode method General Exception:
Message:Impossibile salvare l'allegato. Impossibile aggiungere l'allegato. Nessuna origine dati specificata.
Source:Microsoft Outlook
StackTrace:   at Microsoft.Office.Interop.Outlook.Attachment.SaveAsFile(String Path)
   at SuiteCRMAddIn.ThisAddIn.Base64Encode(Attachment objMailAttachment, MailItem objMail)
Data:System.Collections.ListDictionaryInternal
HResult:-2147467259
Inputs:
Data:image001.png
```

These messages are generated by  SuiteCRMAddIn\ThisAddIn.cs:
after the statement
```
try
                {
                    objMailAttachment.SaveAsFile(Environment.SpecialFolder.MyDocuments.ToString() + "\\SuiteCRMTempAttachmentPath\\" + objMailAttachment.FileName);
                    strRet = System.IO.File.ReadAllBytes(Environment.SpecialFolder.MyDocuments.ToString() + "\\SuiteCRMTempAttachmentPath\\" + objMailAttachment.FileName);
                }

```

I searched the web and i found that "Environment.SpecialFolder.MyDocuments" is a .NET environment costant
http://www.visual-basic-tutorials.com/Tutorials/MsCodes/get-special-directories-path-in-visual-basic.htm

I'm still thinking that the plugin try to save the temporary file in MyDocuments and it failed.
Any solutions?

**Comment by pgorod** [comment]
It's probably a good idea to copy the relevant parts of the forum discussion over here. But the error you posted there seems more informative to me:
```
ArchiveEmail method General Exception:
Message:Accesso al percorso 'MyDocuments\SuiteCRMTempAttachmentPath' negato.
Source:mscorlib
StackTrace: in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
in System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
in System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
in SuiteCRMAddIn.ThisAddIn.Base64Encode(Attachment objMailAttachment, MailItem objMail)
in SuiteCRMAddIn.ThisAddIn.ArchiveEmail(MailItem objMail, Int32 intArchiveType, String strExcludedEmails)
Data:System.Collections.ListDictionaryInternal
HResult:-2147024891 
```
It clearly shows the path (italian: _percorso_) resolving as `MyDocuments\SuiteCRMTempAttachmentPath` which is never going to work.

If I am not mistaken, the bug is in using this to get the special directory:
`Environment.SpecialFolder.MyDocuments.ToString()`
That looks like it's resolving to just `MyDocuments`, which is no good.

If anybody can please test with this instead:
`System.Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)`
which is what every example I've found online recommends. That's surely going to give us a full path, which is what we need.

By the way, I don't think willrennie gets these mention notifications. If I was in his position I would probably also turn them off, to avoid getting spammed all the time by people eager to get his attention. I don't think he's reading this...

**Comment by mayerelyashiv** [comment]
Thank you pgorod.
I don't have a .Net compiler,...

**Comment by CamoMacdonald** [comment]
Resolved in 3.0.0

**Comment by mayerelyashiv** [comment]
Hi CamoMacdonald, from where can i download the 3.0.0 version?

**Comment by CamoMacdonald** [comment]
@mayerelyashiv  You can install the official version from the Suite Store: https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin?tag=suitecrm
However the master and develop branch both have V3

**Comment by mayerelyashiv** [comment]
Sorry, i can't understand: why have i to buy it, if it's free downloable from GitHub? 
It's a matter if i want to donate and support the SuiteCRM Team? (they really deserve it)

**Comment by CamoMacdonald** [comment]
Hi @mayerelyashiv 
The plugin now includes licensing, this is to help maintain the plugin to a high standard and so we can offer continuous support.
The store is where you must get the licence to enable the plugin to function, however all the code we use will remain on GitHub.

**Comment by mayerelyashiv** [comment]
Ok, thank you. 
I definitely agree
